FROM base/archlinux
LABEL maintainer=ci@dh.univie.ac.at \
      vendor=DHUniWien

RUN /usr/bin/pacman --noconfirm --sync --refresh \
 && /usr/bin/pacman --noconfirm --sync python-bottle

RUN /usr/bin/mkdir -p /var/www/moe/

COPY src /var/www/moe
WORKDIR /var/www/moe/

CMD ["/usr/bin/python3", "main.py"]
