---
resources:
    - name: sources
      type: git
      source:
        uri: {{sources-uri}}
        branch: {{sources-branch}}
        paths: [src]

    - name: moe-final-image
      type: docker-image
      source:
        repository: {{moe-final-image}}
        insecure_registries: [ {{insecure-registries}} ]

jobs:
    - name: test
      plan:
        - get: sources
          trigger: true

        - task: task-package

          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: {{moe-ci-image}}
                insecure_registries: [ {{insecure-registries}} ]

            inputs:
              - name: sources

# neradi            run:
# neradi              path: /usr/sbin/python3
# neradi              dir: sources/src
# neradi              args:
# neradi                - "-m unittest"
# neradi                - "discover"
# neradi                - "--start-directory test/"

            run:
              path: task-package.sh
              dir: sources/ci


    - name: package
      plan:
        - get: sources
          trigger: true
          passed: [test]

        - put: moe-final-image
          params:
            # The path of a directory containing a Dockerfile to build.
            build: sources/
