---
resources:
    - name: sources
      type: git
      source:
        uri: {{sources-uri}}
        branch: {{sources-branch}}
        # paths: [src]

    - name: moe-final-image
      type: docker-image
      source:
        repository: {{moe-final-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: version
      type: semver
      source:
        driver: git
        uri: {{version-uri}}
        branch: {{version-branch}}
        file: {{version-file}}
        initial_version: "0.0.0"
        private_key: {{github-private-key}}

jobs:
    - name: test
      plan:
        - get: sources
          trigger: true

        - task: task-package

          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: {{moe-ci-image}}
                insecure_registries: [ {{insecure-registries}} ]

            inputs:
              - name: sources

            # nok: "/usr/bin/python3: No module named  unittest"
            #run:
            #  path: /usr/sbin/python3
            #  dir: sources/src
            #  args:
            #    - "-m unittest"
            #    - "discover"
            #    - "--start-directory test/"

            # ok
            run:
              path: sh
              dir: sources/src
              args:
                - -exc
                - |
                  python3 -m unittest discover --start-directory test/


    - name: package
      plan:
        - put: version
          params:
            bump: patch

        - get: sources
          trigger: true
          passed: [test]

        - put: moe-final-image
          params:
            # The path of a directory containing a Dockerfile to build.
            build: sources/
            dockerfile: sources/ci/Dockerfile-final
            tag: version/version
